// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// InnerVariableDifferencesRcpp
NumericMatrix InnerVariableDifferencesRcpp(NumericVector InputVector, int N);
RcppExport SEXP _BIDistances_InnerVariableDifferencesRcpp(SEXP InputVectorSEXP, SEXP NSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type InputVector(InputVectorSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    rcpp_result_gen = Rcpp::wrap(InnerVariableDifferencesRcpp(InputVector, N));
    return rcpp_result_gen;
END_RCPP
}
// SharedNeighborDistance_Rcpp
NumericMatrix SharedNeighborDistance_Rcpp(NumericMatrix AdjMat, int N, double NumNeighbors);
RcppExport SEXP _BIDistances_SharedNeighborDistance_Rcpp(SEXP AdjMatSEXP, SEXP NSEXP, SEXP NumNeighborsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type AdjMat(AdjMatSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< double >::type NumNeighbors(NumNeighborsSEXP);
    rcpp_result_gen = Rcpp::wrap(SharedNeighborDistance_Rcpp(AdjMat, N, NumNeighbors));
    return rcpp_result_gen;
END_RCPP
}
// fastPdistC
NumericMatrix fastPdistC(NumericMatrix Ar, NumericMatrix Br);
RcppExport SEXP _BIDistances_fastPdistC(SEXP ArSEXP, SEXP BrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type Ar(ArSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Br(BrSEXP);
    rcpp_result_gen = Rcpp::wrap(fastPdistC(Ar, Br));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_BIDistances_InnerVariableDifferencesRcpp", (DL_FUNC) &_BIDistances_InnerVariableDifferencesRcpp, 2},
    {"_BIDistances_SharedNeighborDistance_Rcpp", (DL_FUNC) &_BIDistances_SharedNeighborDistance_Rcpp, 3},
    {"_BIDistances_fastPdistC", (DL_FUNC) &_BIDistances_fastPdistC, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_BIDistances(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
