# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

InnerVariableDifferencesRcpp <- function(InputVector, N) {
    .Call(`_BIDistances_InnerVariableDifferencesRcpp`, InputVector, N)
}

SharedNeighborDistance_Rcpp <- function(AdjMat, N, NumNeighbors) {
    .Call(`_BIDistances_SharedNeighborDistance_Rcpp`, AdjMat, N, NumNeighbors)
}

fastPdistC <- function(Ar, Br) {
    .Call(`_BIDistances_fastPdistC`, Ar, Br)
}

